services:
  ide:
    build:
      dockerfile: Dockerfile.ide
    image: ide:latest
    container_name: ide
    working_dir: /workspace
    volumes:
      - ./.nvim:/root/.config/nvim
      - .:/workspace
    command: sh -c "
        echo '-----' &&
        echo 'Setup complete. IDE is ready for development.' &&
        echo '-----' &&
        sleep infinity
      "

  web:
      image: node:24-alpine3.21
      working_dir: /app
      volumes:
          - ./client-web:/app
      ports:
          - "3000:3000"
      command: sh -c "
        npm install && \
        sleep infinity"
      depends_on:
          - server
  server:
      image: node:24-alpine3.21
      working_dir: /app
      ports:
          - "8000:8000"
      volumes:
          - ./server:/app
      command: sh -c "
        npm install && \
        npm run dev"