import type { Metadata } from "next";
import { Oxanium, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import React from "react";

const oxanium = Oxanium({
	variable: "--font-sans",
	subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
	variable: "--font-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import { Auth_Context_Provider } from "@/context/auth-context";
import { Theme_Provider } from "@/components/theme-provider";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${oxanium.variable} ${sourceCodePro.variable} antialiased`}>
				<Theme_Provider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<Auth_Context_Provider>{children}</Auth_Context_Provider>
				</Theme_Provider>
			</body>
		</html>
	);
}
